begin;

create table if not exists public.reclamaciones (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  created_at timestamptz not null default now(),
  tipo text not null check (tipo in ('Reclamo', 'Queja')),
  nombre text not null check (char_length(nombre) between 3 and 150),
  tipo_documento text not null check (tipo_documento in ('DNI', 'CE', 'Pasaporte')),
  documento text not null check (char_length(documento) between 6 and 20),
  domicilio text not null check (char_length(domicilio) between 5 and 250),
  telefono text not null check (char_length(telefono) between 7 and 20),
  email text not null check (char_length(email) between 5 and 180),
  es_menor boolean not null default false,
  representante_nombre text,
  representante_domicilio text,
  representante_telefono text,
  representante_email text,
  bien_tipo text not null check (bien_tipo in ('Producto', 'Servicio')),
  bien_descripcion text not null check (char_length(bien_descripcion) between 3 and 250),
  monto numeric(12,2) not null check (monto >= 0),
  detalle text not null check (char_length(detalle) between 10 and 2000),
  pedido text not null check (char_length(pedido) between 5 and 1000),
  medio_respuesta text not null check (medio_respuesta in ('Correo electrónico', 'Carta al domicilio')),
  conformidad boolean not null check (conformidad = true),
  conformidad_at timestamptz not null default now(),
  estado text not null default 'Pendiente'
    check (estado in ('Pendiente', 'En atención', 'Atendido')),
  acciones_proveedor text,
  respondido_at timestamptz
);

create index if not exists reclamaciones_created_at_idx
  on public.reclamaciones (created_at desc);
create index if not exists reclamaciones_estado_idx
  on public.reclamaciones (estado);

alter table public.reclamaciones enable row level security;
revoke all on table public.reclamaciones from anon, authenticated;
grant select, insert, update on table public.reclamaciones to service_role;

commit;
